### ISSUE TITLE
Rationale for installing from master

### ISSUE THREAD

**Issue by alextes** [josephfrazier/prettier_d#13]
I tend not to install deps from GitHub unless there's a good reason to.
What's the reason you're not publishing the new version?

Small sidenote: it seems to copied all of the prettier repo in here (also why??) and copied their issue template in the process. Not sure you meant to.

**Comment by alextes** [comment]
Smaller sidenote: somewhere between `1a28295f41c7912cf3ca39c46a5b4d710acf48d7` and `master` things broke.

**Comment by josephfrazier** [comment]
To put it simply, it was easier for me to update prettier_d if it's a fork of prettier (instead of relying on prettier to be installed separately), and if I don't run the build process (because of the way prettier_d overrides some prettier functionality). See https://github.com/josephfrazier/prettier_d/issues/4#issuecomment-450060928 for a bit more context on this change. I expect this to be the same going forward, but if you have ideas for fixing it, feel free to discuss them, or even better, open a PR!

Copying the issue template was a side effect of making this a prettier fork, but it could be changed (again, I'm very open to PRs).

**Comment by alextes** [comment]
👍

**Comment by mikew** [comment]
I've got something working, based off of `eslint_d`. It's not 1:1 with prettier's command line, but as a formatting daemon, it's wicked fast and doesn't need to be a fork of prettier itself.

**Comment by josephfrazier** [comment]
> I've got something working, based off of `eslint_d`. It's not 1:1 with prettier's command line, but as a formatting daemon, it's wicked fast and doesn't need to be a fork of prettier itself.

Oh, I ran across this recently at https://github.com/mikew/prettier_d_slim, and noticed it's using `core_d` (I created an issue for this at https://github.com/josephfrazier/prettier_d/issues/37). Is it faster than `prettier_d`? `prettier_d` is also a fork of `eslint_d`, so I'd be curious to dig in to any speed discrepancy.

---

(responding to @thisguychris's comment at https://github.com/josephfrazier/prettier_d/issues/14#issuecomment-569558805)

> @josephfrazier your welcome, I also appreciate you jumping to my issue and try to work with me, and it's a holiday to boot!
> 
> I'm not sure if this is an excellent place to discuss this, or in #13, but a comfortable middle ground [Github Packages](https://github.com/features/packages). Where it doesn't interfere with the `npm` echo system but make it more convenient for users to install since a registry is an optimized form of installing a package as opposed to installing via GitHub repo. Let me know if you are open with the idea, I can create an issue, and we can discuss from there. Happy Holidays!

I've been curious to try Github Packages, but I wonder if versioning would present any difficulties. It seems like trying to have the same version numbers between `prettier` and `prettier_d` might not be easily done, since `prettier_d` can have its own bugfixes outside of the forked `prettier` code. On the other hand, perhaps `prettier_d` should go back to having versioned releases even if they don't correspond to `prettier` versions (for example, it'd probably need to start with `v6.0.1` since `6.0.0` is currently in the `package.json`).

I'm not sure if installation would be very optimized over the installation from the repo though, since `prettier_d` doesn't currently use `prettier`'s build process to bundle dependencies.

What do you think?

**Comment by chiefjester** [comment]
hey @josephfrazier, sorry for the late reply, been busy with work and the holidays. So I would like to chime in on some items.

> Oh, I ran across this recently at https://github.com/mikew/prettier_d_slim, and noticed it's using core_d (I created an issue for this at #37). Is it faster than prettier_d? prettier_d is also a fork of eslint_d, so I'd be curious to dig in to any speed discrepancy.

I'd like to know this well, maybe we can include some sort of benchmark we can run on GitHub Actions that'll update our readme of the scores?

> I've been curious to try Github Packages, but I wonder if versioning would present any difficulties. It seems like trying to have the same version numbers between prettier and prettier_d might not be easily done, since prettier_d can have its own bugfixes outside of the forked prettier code. 

That is indeed a problem if you wanted it to be 1:1. It depends on what your definition of a fork. If `prettier_d` is meant to be a thin wrapper of `prettier`, daemonizing it. Then I think it should have its own versioning number, if you want it as close as 1:1 I guess we can stick with major and minor numbers.

> I'm not sure if installation would be very optimized over the installation from the repo though, since prettier_d doesn't currently use prettier's build process to bundle dependencies.

If you're talking about installing via GitHub links, then yes, `npm` is not optimized for installing this. It's probably how they handle dependencies, and they are indeed really fast if you host in a registry instead of a repo.

## I just tried this in my machine, 1st pass, on a blank repo:

_prettier_d took 51 secs to install_
![prettier_d took 51 secs to install](https://monosnap.com/image/19mOrKJm2Jy1ZKeOLfOqB7Tkvp5VEa)

_prettier took 8.5 secs_
![prettier took 8.5 secs to install](https://monosnap.com/image/8gpLM29BLn5d6Yz84gTLGqiGrof9QV)

## Here's a second pass, on a blank repo

_prettier took 1.2 secs to install_
![prettier took 1.2 secs to install](https://monosnap.com/image/vDx7woN4N2z5SxY361mUUPaGJAMqC3)

_prettier_d took 37.8 secs to install_
![prettier_d took 37.8 secs to install](https://monosnap.com/image/73pqYgAfpCgN2e53RrmypURdVajtL9)

It seems that `npm` made some optimizations installing packages from the registry as opposed to GitHub repos.

**Comment by chiefjester** [comment]
#### I would like to add these benchmark on the last` prettier_d` version (5.7.4) that was installable via `npm`:

_prettier_d took 5.7 secs_
![prettier_d took 5.7 secs](https://monosnap.com/image/lcJ8Zh5HCsNvtCwa2akVhps2gtjH8v)

_prettier_d took 2.5 secs on second pass_
![Alt text](https://monosnap.com/image/OJ6VaBjNF82M13rINZey2c9vzn2OjY)

**Comment by josephfrazier** [comment]
> I'd like to know this well, maybe we can include some sort of benchmark we can run on GitHub Actions that'll update our readme of the scores?

Oh yeah, those scores I put in the readme are quite outdated and hardware-dependent. I'm sure there's something out there that could templatize/auto-update them, but haven't bothered looking for it.

> That is indeed a problem if you wanted it to be 1:1. It depends on what your definition of a fork. If `prettier_d` is meant to be a thin wrapper of `prettier`, daemonizing it. Then I think it should have its own versioning number, if you want it as close as 1:1 I guess we can stick with major and minor numbers.

Unfortunately, since I started publishing `prettier_d` with version numbers continued from upstream's `eslint_d`, the version is much farther ahead of Prettier's version. Perhaps incrementing `prettier`s major version by 100 or so could work, though. For example, the next `prettier_d` release would be `101.19.1`, since Prettier is currently at `1.19.1`

> > I'm not sure if installation would be very optimized over the installation from the repo though, since prettier_d doesn't currently use prettier's build process to bundle dependencies.
> 
> If you're talking about installing via GitHub links, then yes, `npm` is not optimized for installing this. It's probably how they handle dependencies, and they are indeed really fast if you host in a registry instead of a repo.
> 
> ## I just tried this in my machine, 1st pass, on a blank repo:
> _prettier_d took 51 secs to install_
> ![prettier_d took 51 secs to install](https://camo.githubusercontent.com/b6c0219f15649428b6b28df01a7731942bd9fc9e/68747470733a2f2f6d6f6e6f736e61702e636f6d2f696d6167652f31396d4f724b4a6d324a79315a4b654f4c664f714237546b767035564561)
> 
> _prettier took 8.5 secs_
> ![prettier took 8.5 secs to install](https://camo.githubusercontent.com/7dab861c57e2701472f9291166ad0f5034f7bf26/68747470733a2f2f6d6f6e6f736e61702e636f6d2f696d6167652f3867704c4d3239424c6e356436597a383467544c47716947726f66395156)
> 
> ## Here's a second pass, on a blank repo
> _prettier took 1.2 secs to install_
> ![prettier took 1.2 secs to install](https://camo.githubusercontent.com/6924737a28890f550da845516633541cadc8a303/68747470733a2f2f6d6f6e6f736e61702e636f6d2f696d6167652f76447837776f4e344e327a355378593336316d55555061474a414d714333)
> 
> _prettier_d took 37.8 secs to install_
> ![prettier_d took 37.8 secs to install](https://camo.githubusercontent.com/2e7f02703f490b0694dacd0d050decc9f54eafbb/68747470733a2f2f6d6f6e6f736e61702e636f6d2f696d6167652f37337071596741667043674e3265353352726d797055526456616a744c39)
> 
> It seems that `npm` made some optimizations installing packages from the registry as opposed to GitHub repos.

I think the difference here isn't so much that the `prettier_d` code is being pulled from github vs NPM, it's that all of `prettier_d`'s dependencies must be downloaded separately (from NPM), whereas Prettier has a build process that results in a zero-dependency published package. `prettier_d` currently does not use that build process, due to some of the changes made, but if it did, I imagine the install time would be much more similar to Prettier's. Until then, however, I suspect that publishing to NPM wouldn't actually help that much.

For what it's worth, `prettier_d` is really only meant to be used as a development dependency IMO, so I'm frankly not as concerned with install time as I would be if it were meant to be a production dependency. However, if you/anyone wants to help with getting the build/publish process working again, I'd be happy to provide  pointers/knowledge!

**Comment by mikew** [comment]
> Is it faster than prettier_d? prettier_d is also a fork of eslint_d, so I'd be curious to dig in to any speed discrepancy.

I can do a benchmark. But with prettier_d being a fork, recommended to be installed from GitHub, makes it a non-starter for me.

**Comment by chiefjester** [comment]
> Unfortunately, since I started publishing prettier_d with version numbers continued from upstream's eslint_d, the version is much farther ahead of Prettier's version. Perhaps incrementing prettiers major version by 100 or so could work, though. For example, the next prettier_d release would be 101.19.1, since Prettier is currently at 1.19.1

Forgive me for my naiveness, but is the prettier_d to follow eslint_d or prettier or both? I guess I'm fine as long as there is 1:1 mapping between versions.

> prettier_d currently does not use that build process, due to some of the changes made,

Oh wow, upon inspection, I do see a lot of dependencies prettier_d has.

> For what it's worth, prettier_d is really only meant to be used as a development dependency IMO, so I'm frankly not as concerned with install time as I would be if it were meant to be a production dependency

True, that's my use case as well, I guess it depends on the usage if they have it installed globally or as a `devDependency` of a repo. For a team that deals with hundreds of repositories though, 50 seconds is too much. Improving install time is an improvement of Developer Experience, where I think this project is aimed at.

**Comment by josephfrazier** [comment]
> I can do a benchmark. But with prettier_d being a fork, recommended to be installed from GitHub, makes it a non-starter for me.

Thanks for the additional detail, I might start publishing again using the +100 major version scheme described above. I'll try to let you know if I do! Until then, I think you can get most of the benefit of versioned releases by installing a particular commit of the repo, for example:

```bash
yarn add --dev https://github.com/josephfrazier/prettier_d#faf45d2ac9acc9b919d13ea058f8b28d4d947baa
npm install --save-dev https://github.com/josephfrazier/prettier_d#faf45d2ac9acc9b919d13ea058f8b28d4d947baa
```

> Forgive me for my naiveness, but is the prettier_d to follow eslint_d or prettier or both? I guess I'm fine as long as there is 1:1 mapping between versions.

Great question! `prettier_d` was originally forked from `eslint_d` and tried to use whichever Prettier was installed in the same project. At that point, I continued using the same version numbers from `eslint_d` (though I now realize there probably wasn't any good reason for that). However, I eventually found it too difficult to support new Prettier options, so shifted the code over to being a fork of Prettier as well. I'm no longer tracking `eslint_d` updates, so `prettier_d` is really only a fork of Prettier at this point.

> True, that's my use case as well, I guess it depends on the usage if they have it installed globally or as a devDependency of a repo. For a team that deals with hundreds of repositories though, 50 seconds is too much. Improving install time is an improvement of Developer Experience, where I think this project is aimed at.

That's a good point, about improving developer experience. I'd like to think npm/yarn caching helps with install time across multiple repos, but I don't know how much that's the case. I can't commit to trying to eliminate the dependencies from `prettier_d` at this point, but I'll keep it in mind for when I find time, and am still willing to help you or anyone else give it a shot!

**Comment by josephfrazier** [comment]
closing, as this project is no longer maintained
