### ISSUE TITLE
Please upgrade prettier to 1.19

### ISSUE THREAD

**Issue by trongthanh** [josephfrazier/prettier_d#25]
Mainstream prettier has been updated to 1.19 with a few more options and new JS syntax support: Vue file indent; optional chaining...

Prettier in this library is a bit out date. Please upgrade it or if possible, make prettier_d use the standalone prettier runtime installed globally.

**Environments:**
- Prettier Version: 1.16.4
- Running Prettier via: CLI
- Runtime: Node.js 12
- Operating System: macOS

Thanks.

**Comment by josephfrazier** [comment]
Thanks for the reminder, @trongthanh. `prettier_d` is now a fork of Prettier (because I couldn't get certain features working otherwise) and [does not have versioned releases anymore](https://github.com/josephfrazier/prettier_d/tree/75d0d5101903a81357e3e952ffa68fb86eb5ba57#install), but I can try to merge Prettier 1.19.1 (the latest version at the time of writing) into this repo and seeing how it goes. Stay tuned for a PR!
