### ISSUE TITLE
v6 hangs if installation is not writable

### ISSUE THREAD

**Issue by alinnow** [josephfrazier/prettier_d#41]
After upgrading to v6, running `prettier_d start` (I presume that this is optional anyway) and then `prettier_d src/index.js` appears to hang indefinitely without any output.

`strace` yields

```
access("/nix/store/iz1s2l7khy4mwqls7v802nklkhz39qwh-node_prettier_d-1.19.1/lib/node_modules/prettier_d/lib/.prettier_d", F_OK) = -1 ENOENT (No such file or directory)
```

about once per second. This file does indeed not exist. I'm running `prettier_d` on NixOS, but this happens regardless of whether `prettier_d` is installed directly in NixOS or run via `npx`. I suppose it was commit https://github.com/josephfrazier/prettier_d/commit/96e8213d9edb1b7cbb2f7d2acff979031ef60139 that breaks running on NixOS; everything under `/nix/store` is mutable only via the package manager. Presumably this commit also does not work if `prettier_d` is installed via `sudo npm install -g` either.

I reverted back to 565a176df79fb50e878058d3af819b7787f5a03e and `prettier_d` works as expected.

If reverting 96e8213 is not an option, a better option might be to store `.prettier_d` alongside the `package.json` that `npm` commands would use, perhaps via https://www.npmjs.com/package/find-project-root (already in dependencies).

**Comment by josephfrazier** [comment]
Hey Alan, thanks for the report. It's neat to come across someone using NixOS! I haven't tried it or Nix myself, but I've heard a lot of good things.

I'll [revert](https://github.com/josephfrazier/prettier_d/pull/42) that commit for now, since no one has complained about any conflict between multiple versions of `prettier_d`. I like the idea of storing the file on a per-project basis, so I might try to put that change together separately.
